name: Actions Workflow

on: [push]
# note : uses: actions/hello-world-javascript-action@v1 reference with commits or branches
jobs:
  run-gitgub-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITGUB_SHA
          echo $GITGUB_REPOSITORY
          echo $GITGUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GITGUB_REPOSITORY
          # git checkout $GITGUB_SHA
      - name: Checkout
        uses: actions/checkout@v1
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Jean
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
